function T = reshapeToTensor(A, m, n1, n2)
% function to reshape the second order derivative of a vector function with
% m components with respect to vectors of n1 and n2 components (as
% generated by ADiGator) with its corresponding tensor representation
%
% authored by Riccardo Minnozzi, 06/2024

T = zeros(m, n1, n2);
for k = 1:n2
    % loop over all the indexes of the second differential

    for i = 1:m
        % loop over all the function components

        T(i, :, k) = A(m * (k - 1) + i, :);

    end
end

end

