function obj = createStageCollocationBuildFile(obj)
% function that creates the wrapper file for the stage collocation control
% file

% get the phase number and the inputs dimensions
i = obj.ID(2);
[nx, nu, nw, ~, ~, ~] = getInputSizes(obj);
nX = nx + nu + nw;

% create the stage size control file
obj.tPoint_file = strcat("tPoint_", string(i));
id = fopen(strcat(obj.tPoint_file, ".m"), "w+");
fprintf(id, strcat("function tPoint = ", obj.tPoint_file, "(k, X) \n"));
commentStr = strcat("%% Stage collocation wrapper function for phase ", ...
    string(i), ",\n%% automatically generated by the PhaseManager class on ", ...
    datestr(datetime("now")), "\n");
fprintf(id, commentStr);
% set the wrapped inputs
fprintf(id, strcat("x = X(1: ", string(nx), ", 1); \n"));
fprintf(id, strcat("u = X(", string(nx + 1), ": ", ...
    string(nx + nu), ", 1); \n"));
fprintf(id, strcat("w = X(", string(nx + nu + 1), ": ", ...
    string(nX), ", 1); \n"));
% set the auxiliary functions and output
fprintf(id, "\n");
fprintf(id, strcat("tPoint = ", obj.stageCollocationFile, "(k, x, u, w); \n"));
fprintf(id, "end");
fclose(id);
end

