function obj = createAugmentedStateDerivativeBuildFile(obj)
% function that creates the augmented state derivative wrapper file

% get the phase number and the inputs dimensions
i = obj.ID(2);
[nx, nu, nw, ~, ~, ~] = getInputSizes(obj);
nX = nx + nu + nw;

% create the augmented state derivative wrapper file
obj.ft_file = strcat("ft_", string(i));
id = fopen(strcat(obj.ft_file, ".m"), "w+");
fprintf(id, strcat("function Xdot = ", obj.ft_file, ...
    "(t, X) \n"));
commentStr = strcat("%% Augmented state derivative wrapper function for phase ", ...
    string(i), ",\n%% automatically generated by the PhaseManager class on ", ...
    datestr(datetime("now")), "\n");
fprintf(id, commentStr);
% add line to increase corresponding feval count
fprintf(id, "%% Increase dynamics function evaluations \n");
fprintf(id, "global HOIST_fevalsCount_ft \n");
fprintf(id, "HOIST_fevalsCount_ft = HOIST_fevalsCount_ft + 1; \n");
% set the wrapped inputs
fprintf(id, strcat("x = X(1: ", string(nx), ", 1); \n"));
fprintf(id, strcat("u = X(", string(nx + 1), ": ", ...
    string(nx + nu), ", 1); \n"));
fprintf(id, strcat("w = X(", string(nx + nu + 1), ": ", ...
    string(nX), ", 1); \n"));
% set the auxiliary functions and output
fprintf(id, "\n");
fprintf(id, strcat("xdot = ", obj.stateDerivativeFile, "(t, x, u, w); \n"));
fprintf(id, strcat("udot = zeros(", string(nu), ", 1); \n"));
fprintf(id, strcat("wdot = zeros(", string(nw), ", 1); \n"));
fprintf(id, strcat("Xdot = [xdot; udot; wdot]; \n"));
fprintf(id, "end");
fclose(id);

end

